[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
    "npm install",
    "cd backend && npm install",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npx vite build"
]

[start]
cmd = "cd backend && npm start"
